"""
Generate plan_inference.pkl from plan.pkl with default inference parameters.

nnDetection requires plan_inference.pkl for prediction, which is normally
generated by running sweep after training. This script creates one with
default parameters if sweep was not run.

Usage:
    python generate_plan_inference.py --plan /path/to/plan.pkl --output /path/to/plan_inference.pkl

If no paths specified, searches the training directory from config.json.
"""

import argparse
import json
import os
import pickle
import sys
from pathlib import Path


def generate_plan_inference(plan_path, output_path):
    """Generate plan_inference.pkl from plan.pkl with default parameters."""

    with open(plan_path, "rb") as f:
        plan = pickle.load(f)

    print(f"Loaded plan.pkl from: {plan_path}")
    print(f"  Keys: {list(plan.keys())}")

    if "inference_plan" in plan:
        print("  plan already contains inference_plan, no changes needed.")
    else:
        # Default inference parameters (from BoxEnsemblerSelective)
        inference_plan = {
            "model_iou": 0.1,
            "model_score_thresh": 0.0,
            "model_topk": 1000,
            "model_detections_per_image": 100,
            "ensemble_iou": 0.5,
            "ensemble_topk": 1000,
            "remove_small_boxes": 0.01,
            "ensemble_score_thresh": 0.0,
        }
        plan["inference_plan"] = inference_plan
        print(f"  Added default inference_plan: {inference_plan}")

    with open(output_path, "wb") as f:
        pickle.dump(plan, f)

    print(f"Saved plan_inference.pkl to: {output_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate plan_inference.pkl from plan.pkl")
    parser.add_argument("--plan", type=str, default=None,
                        help="Path to plan.pkl")
    parser.add_argument("--output", type=str, default=None,
                        help="Output path for plan_inference.pkl")
    parser.add_argument("--training_dir", type=str, default=None,
                        help="Training directory (auto-find plan.pkl)")
    args = parser.parse_args()

    if args.plan:
        plan_path = args.plan
        output_path = args.output or str(Path(args.plan).parent / "plan_inference.pkl")
    elif args.training_dir:
        tdir = Path(args.training_dir)
        # Search for plan.pkl in preprocessed dirs or training dir
        candidates = list(tdir.glob("plan.pkl")) + list(tdir.glob("**/plan.pkl"))
        if not candidates:
            print(f"ERROR: No plan.pkl found in {tdir}")
            sys.exit(1)
        plan_path = str(candidates[0])
        output_path = args.output or str(tdir / "plan_inference.pkl")
    else:
        # Try to load from config.json
        config_path = Path(__file__).parent / "config.json"
        if config_path.exists():
            with open(config_path) as f:
                cfg = json.load(f)
            tdir = Path(cfg["paths"].get("training_dir", ""))
            if tdir.exists():
                plan_path = str(tdir / "plan.pkl")
                output_path = str(tdir / "plan_inference.pkl")
            else:
                print("ERROR: Provide --plan or --training_dir argument")
                sys.exit(1)
        else:
            print("ERROR: Provide --plan or --training_dir argument")
            sys.exit(1)

    if not os.path.exists(plan_path):
        print(f"ERROR: plan.pkl not found at {plan_path}")
        sys.exit(1)

    generate_plan_inference(plan_path, output_path)


if __name__ == "__main__":
    main()
